refacted config/pipeline-java.yml

diff --git a/config/pipeline-java-war.yml b/config/pipeline-java-war.yml
--- a/config/pipeline-java-war.yml
+++ b/config/pipeline-java-war.yml
@@ -1,16 +1,23 @@
 
 pipeline:
-  name: javawar
+  name: java-war
   identifiers:
   - pom.xml
-  targets:
-  - target/${app}.war
-  - target/${app}-${version}.war
-  fromdir: target/deployments
   deploymentfile: ROOT.war
   imagestream: s2i-java-war:latest
-  versionfrom: pom.xml
-  options: -Xms128m -Xmx512m -Xss512k
-  buildcommand: mvn clean install -U
+  env:
+  - name: APP_OPTIONS
+    value: -Xms128m -Xmx512m -Xss512k -XX:+ExitOnOutOfMemoryError
+  - name: SPRING_PROFILES_ACTIVE
+    value: ${profile}
+  - name: TZ
+    value: Asia/Shanghai
+  script: |
+    mvn clean package -U -Dmaven.test.skip=true -Djava.net.preferIPv4Stack=true
+    if [[ $? == 0 ]]; then
+      echo "Successful."
+    else
+      echo "Failed!"
+    fi
 
 
